FinalProject/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Data;
using FinalProject.Models;
using FinalProject.Services.Authors;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject.Controllers
{
   
    [Authorize(Roles = "Admin,Manager,User")]
    public class AuthorsController : Controller
    {
        //public readonly AppDBContext _context;

        public readonly AuthorsService _context;

        public AuthorsController(AuthorsService context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult Create(Authors teacher)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Authors.Add(teacher);
        //        _context.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    else
        //        return View();
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Author_id,Author_name")] Authors author)
        {
            if (ModelState.IsValid)
            {
                await _context.AddAndSave(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        //public IActionResult Index()
        //{
        //    return View(_context.Authors);
        //}

        public async Task<IActionResult> Index()
        {
            return View(await _context.GetAll());
        }

        //public IActionResult Update(int id)
        //{
        //    return View(_context.Authors.Where(a => a.Author_id == id).FirstOrDefault());
        //}

        //[HttpPost]
        //[ActionName("Update")]
        //public IActionResult Update_Post(Authors author)
        //{
        //    _context.Authors.Update(author);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //[HttpPost]
        //public IActionResult Delete(int id)
        //{
        //    var role = _context.Authors.Where(a => a.Author_id == id).FirstOrDefault();
        //    _context.Authors.Remove(role);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        // GET: Coaches/Edit/5
        public async Task<IActionResult> Update(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.GetById(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, [Bind("Author_id,Aithor_name")] Authors author)
        {
            if (id != author.Author_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.UpdateAndSave(author);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.CoachExists(author.Author_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            return View(author);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.GetById((string)id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Coaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _context.DeleteAndSave(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

FinalProject/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Data;
using FinalProject.Models;
using FinalProject.Services.Books;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject.Controllers
{
    
    [Authorize(Roles = "Admin,User,Manager")]
    public class BooksController : Controller
    {
        private readonly BooksService _booksService;

        //[TempData]
        //public string Message { get; set; }

        public BooksController(BooksService booksService)
        {
            _booksService = booksService;
        }

        public async Task<IActionResult> Index()
        {
            var surveys = await _booksService.GetAllBooks();
            
            //Message = $"Session saves Books";
            return View(surveys);
        }

        // GET: Equipments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _booksService.GetById((string)id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        public async Task<IActionResult> Create()
        {
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Full_Name");
            //ViewData["SurveyId"] = new SelectList(_context.Surveys, "Id", "Question");
            ViewData["Pub_id"] = new SelectList(await _booksService.GetAllPublishers(), "Pub_id", "Pub_name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Book_id,Book_title,Book_page,Book_pub,Book_shortDec,Book_dec,Pub_id")] Books equipment)
        {
            if (ModelState.IsValid)
            {
                await _booksService.AddAndSave(equipment);
                return RedirectToAction(nameof(Index));
            }

            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Full_Name", user_Answers.UserId);
            //ViewData["SurveyId"] = new SelectList(_context.Surveys, "Id", "Question", user_Answers.SurveyId);
           ViewData["Pub_id"] = new SelectList(await _booksService.GetAllPublishers(), "Pub_id", "Pub_name", equipment.Pub_id);
            return View(equipment);
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _booksService.GetById(id);
            if (author == null)
            {
                return NotFound();
            }
            ViewData["Pub_id"] = new SelectList(await _booksService.GetAllPublishers(), "Pub_id", "Pub_name", author.Pub_id);
            return View(author);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, [Bind("Book_id,Book_title,Book_page,Book_pub,Book_shortDec,Book_dec,Pub_id")] Books author)
        {
            if (id != author.Book_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _booksService.UpdateAndSave(author);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_booksService.BookExists(author.Book_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }


    }
}

FinalProject/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject.Controllers
{
    public class MainController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalProject/Controllers/UserssController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Data;
using FinalProject.Models;
using FinalProject.Services.Userss;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject.Controllers
{
    
    [Authorize(Roles = "Admin")]
    public class UserssController : Controller
    {
        private readonly UserssService _service;
        private readonly UserManager<Userss> _userManager;

        //[TempData]
        //public string Message { get; set; }

        public UserssController(UserssService service, UserManager<Userss> userManager)
        {
            _service = service;
            _userManager = userManager;
        }

        // GET: /<controller>/
    
        public async Task<IActionResult> Index()
        {
            //if (string.IsNullOrEmpty(HttpContext.Session.GetString("Message")))
            //{
            //    HttpContext.Session.SetString("Message", "Hello from session");
            //}
            //Message = HttpContext.Session.GetString("Message");
            //return View(await _service.GetAllUsers());
            var users = await _service.GetAll();
            return View(users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RegisterViewModel model)
        {

            if (ModelState.IsValid)
            {
                var user = new Userss
                {
                    UserName = model.Email,
                    PasswordHash = model.Password,
                    FullName = model.Full_Name
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                //await _usersService.AddAndSave(user);
                //return RedirectToAction(nameof(Index));
                if (result.Succeeded)
                {
                    return RedirectToAction("index", "/Userss");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }




        // GET: Equipment/Edit/5
        public async Task<IActionResult> Update(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _service.GetById((string)id);
            if (user == null)
            {
                return NotFound();
            }
            //ViewData["Role_id"] = new SelectList(await _service.GetAllRoles(), "Role_id", "Role_idd", user.Role_id);
            return View(user);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, [Bind("User_id,Username,Password,FullName")]  Userss user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAndSave(user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["RoomId"] = new SelectList(await _service.GetAllRoles(), "Role_id", "Role_id", user.Role_id);
            return View(user);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            await _service.DeleteAndSave(id);
            return RedirectToAction(nameof(Index));
        }

        


        ////VerifyUsername
        //[AcceptVerbs("Get", "Post")]
        //public IActionResult VerifyUsername(string username)
        //{
        //    if (_service.Userss.Any(m => m.Username.ToLower() == username.ToLower()))
        //    {
        //        return Json($"Username {username} is already in use.");
        //    }

        //    return Json(true);
        //}

    }
}

FinalProject/Views/Shared/_Layout.cshtml
@using FinalProject.Models;
@using Microsoft.AspNetCore.Identity;
@using Microsoft.Extensions.DependencyInjection.Extensions
@inject SignInManager<Userss> SignInManager

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/css/bootstrap.css")" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container d-flex justify-content-between">
        <a class="nav-link" asp-controller="Main" asp-action="Index" style="color: white;">
                <img src="/img/agenda.png" style="height:26px; width:auto;">
            Book Lovers
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Administration" asp-action="ListRoles">Roles</a>
            </li>
            
/**/<li class="nav-item">
                <a class="nav-link" asp-controller="Userss" asp-action="Index">Users</a>
            </li>
            
/**/<li class="nav-item">
                <a class="nav-link" asp-controller="Authors" asp-action="Index">Authors</a>
            </li>
            
/**/<li class="nav-item">
                <a class="nav-link" asp-controller="Books" asp-action="Index">Books</a>
            </li>
            
/**/<li class="nav-item">
                <a class="nav-link" asp-controller="BooksHaveAuthors" asp-action="Index">BooksHaveAuthors</a>
            </li>
            
/**/<li class="nav-item">
                <a class="nav-link" asp-controller="BooksInventory" asp-action="Index">BookInventory</a>
            </li>


}
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Manager"))
                {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Books" asp-action="Index">Books</a>
                </li>
                
/**/<li class="nav-item">
                    <a class="nav-link" asp-controller="Authors" asp-action="Index">Authors</a>
                </li>
                
/**/<li class="nav-item">
                    <a class="nav-link" asp-controller="BooksHaveAuthors" asp-action="Index">BooksHaveAuthors</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Publishers" asp-action="Index">Publishers</a>
                </li>
                
                }@if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
                {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Books" asp-action="Index">Books</a>
                </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Authors" asp-action="Index">Authors</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" asp-controller="Publishers" asp-action="Index">Publishers</a>
                    </li>
}
            </ul>

            <ul class="navbar-nav ml-auto">
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <form method="post" asp-controller="account" asp-action="logout">
                            <button type="submit" style="width:auto"
                                    class="btn btn-outline-info my-2 my-sm-0">
                                Logout @User.Identity.Name
                            </button>
                        </form>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="btn btn-outline-info my-2 my-sm-0" asp-controller="account" asp-action="login">
                            Login
                        </a>
                    </li>
                }
            </ul>

        </div>
           </div>
    </nav>

    <br />

    <div class="container">
        @RenderBody()
    </div>
    <div style="margin:15%">
    </div>
    <div class="container text-center" >
        @{
        if (TempData.Peek("Message") != null)
        {
            <p class="text-secondary">@TempData.Peek("Message")</p>
            }
            else
            {
        <p class="text-secondary"> You did not enter portal</p>
            }
        }
    </div>
</body>
</html> 